<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Adds temporary password support to CK.DB.User.UserPassword: a IsTemporary bit on CK.tUserPassword, carried by the SetPassword command and exposed on the user profile as IsTemporaryPassword.</Description>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="**\*.sql;**\*.tql;**\*.y4" Exclude="bin\**;obj\**;CodeCakeBuilder\**;packages\**;@(EmbeddedResource)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.DB.User.UserPassword\CK.DB.User.UserPassword.csproj" />
    <ProjectReference Include="..\CK.IO.User.UserPassword.Reset\CK.IO.User.UserPassword.Reset.csproj" />
  </ItemGroup>
</Project>
